[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
fosho_program = "5ojhS89XpkvrSyagCddG7fv4wh2ffx8kVA6ABDYttZdN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "../../../sol/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
